# Generated by Django 2.1.5 on 2019-02-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250, unique=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=12)),
                ('address_line1', models.CharField(blank=True, max_length=125)),
                ('city', models.CharField(blank=True, max_length=125)),
                ('state', models.CharField(blank=True, max_length=125)),
                ('logo', models.ImageField(blank=True, upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_diagnose.CompanyDetail')),
            ],
            options={
                'verbose_name_plural': 'CompanyTests',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=125)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=125)),
                ('city', models.CharField(blank=True, max_length=125)),
                ('state', models.CharField(blank=True, max_length=125)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=12)),
                ('suitable_date', models.CharField(blank=True, max_length=12)),
                ('suitable_time', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=125)),
                ('test_details', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Tests',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='companytests',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_diagnose.Tests'),
        ),
    ]
