# Generated by Django 2.1.5 on 2019-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
