# Generated by Django 2.1.5 on 2019-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0002_companydetail_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='contact_no',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='phone_no',
            field=models.BigIntegerField(blank=True),
        ),
    ]
