# Generated by Django 2.1.5 on 2019-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0003_auto_20190208_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='address_line1',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='city',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='state',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address_line_1',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='city',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='state',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='suitable_date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='suitable_time',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user_name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_details',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_name',
            field=models.CharField(max_length=125),
        ),
    ]
