# Generated by Django 2.1.5 on 2019-02-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0004_auto_20190208_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
