# Generated by Django 2.1.5 on 2019-02-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0005_auto_20190210_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
