# Generated by Django 2.1.5 on 2019-02-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0008_auto_20190210_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='company_id',
        ),
    ]
