# Generated by Django 2.1.5 on 2019-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0009_remove_companydetail_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='test_name',
            field=models.CharField(default='NULL', max_length=125),
        ),
    ]
