# Generated by Django 2.1.5 on 2019-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0010_orderinfo_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
    ]
